volumes:
  pg_data_local:

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: patrol_local
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "patrol_local"]
      interval: 5s
      timeout: 5s
      retries: 5

  validator:
    init: true
    depends_on:
      - db
    build:
      dockerfile: validator.dockerfile
      context: .
    pull_policy: always
    restart: always
    environment:
      DB_URL: postgresql+asyncpg://patrol_local:password@db:5432/patrol_local
      ENABLE_AUTO_UPDATE: 0
      WALLET_NAME: khaicoldkey
      HOTKEY_NAME: khaihotkey1
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
      - /root/sample:/patrol/sample

  validator-sync:
    init: true
    depends_on:
      - db
    build:
      dockerfile: validator-sync.dockerfile
      context: .
    pull_policy: always
    restart: always
    environment:
      DB_URL: postgresql+asyncpg://patrol_local:password@db:5432/patrol_local
      ENABLE_AUTO_UPDATE: 0
      WALLET_NAME: khaicoldkey
      HOTKEY_NAME: khaihotkey1
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets:ro
